{
 "title": "Cockpit",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(reboot_required, instance)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_load_average_10s{instance=~\"$instance\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host", "type": "dashlist", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 } },
  { "title": "Services", "type": "dashlist", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 } },
  { "title": "External", "type": "dashlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 } },
  { "title": "Security", "type": "dashlist", "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 } },
  { "title": "Docker", "type": "dashlist", "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 } },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Reboot required",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reboot_required{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Nextcloud Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_up" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{instance=~\"$instance\",image!=\"\",name=~\"^$container.*$\"}[1m])) / count(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{instance=~\"$instance\",image!=\"\",name=~\"^$container.*$\"})) / sum(node_memory_MemTotal_bytes{instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Storage Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance\",fstype=\"ext4\"} - node_filesystem_free_bytes{instance=~\"$instance\",fstype=\"ext4\"}) / node_filesystem_size_bytes{instance=~\"$instance\",fstype=\"ext4\"}  * 100",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "SMART DIsk Health",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 18 },
   "targets": [
    {
     "expr": "smartmon_device_smart_healthy{instance=\"$instance\"}",
     "legendFormat": "{{ disk }}"
    }
   ]
  },
  {
   "title": "Certificate expiry",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=\"blackboxexporter\"} - time()) / 86400",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Roomba Battery",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "roomba_battery_percent{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Raid Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_state{instance=~\"$instance\",state=\"active\"}) / count(node_md_state{instance=~\"$instance\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "Available Security updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_updates_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Last Backup State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rsync_success" }
   ]
  },
  {
   "title": "Bin Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "roomba_bin_full{instance=\"$instance\"}",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$instance\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - (node_memory_MemFree_bytes{instance=~\"$instance\"} + node_memory_Buffers_bytes{instance=~\"$instance\"} + node_memory_Cached_bytes{instance=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{instance=~\"$instance\",image!=\"\",container_label_org_label_schema_group=\"\",name=~\"^$container.*$\"}[1m])) / scalar(count(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{instance=~\"$instance\",image!=\"\",name=~\"^$container.*$\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container I/O Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(irate(container_fs_reads_bytes_total{instance=~\"$instance\",name=~\"^$container.*$\"}[5m]))",
     "legendFormat": "r {{ name }}"
    },
    {
     "expr": "sum by (name)(irate(container_fs_writes_bytes_total{instance=~\"$instance\",name=~\"^$container.*$\"}[5m]))",
     "legendFormat": "w {{ name }}"
    }
   ]
  },
  {
   "title": "Fritzbox Connection Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_wan_connection_uptime_seconds",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "{{ instance }} - {{ gateway }}",
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "uptime" }
     ]
    }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second*10^-6",
     "legendFormat": "{{ instance }} | Download Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second*10^-6",
     "legendFormat": "{{ instance }} | Upload Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Current Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "tasmota_power_watt{instance=\"$instance\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  }
 ]
}