{
 "title": "Host",
 "description": "Host metrics",
 "tags": [
  "system",
  "host"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(reboot_required, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Reboot required",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reboot_required{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Available Security updates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "security_updates_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$instance\"} - node_boot_time_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_cpu_cores{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$instance\",fstype=\"ext4\"}",
     "legendFormat": "{{ device }} at {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{instance=~\"$instance\"}",
     "legendFormat": "running"
    },
    {
     "expr": "node_procs_blocked{instance=~\"$instance\"}",
     "legendFormat": "blocked by I/O"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " irate(node_intr_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$instance\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - (node_memory_MemFree_bytes{instance=~\"$instance\"} + node_memory_Buffers_bytes{instance=~\"$instance\"} + node_memory_Cached_bytes{instance=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\",device!=\"lo\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\",device!=\"lo\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance\"} - node_memory_SwapFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{instance=~\"$instance\"}[1m]) * 4096 or irate(node_vmstat_pswpin{instance=~\"$instance\"}[5m]) * 4096",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_vmstat_pswpout{instance=~\"$instance\"}[1m]) * 4096 or irate(node_vmstat_pswpout{instance=~\"$instance\"}[5m]) * 4096",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}