{
 "title": "FRITZ!Box Status",
 "description": "Monitor FRITZ!Box routers using prometheus and fritzbox_exporter",
 "tags": [
  "external",
  "network"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(reboot_required, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gateway_device_modelname{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fritzbox Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_uptime_seconds{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "uptime" }
     ]
    }
   ]
  },
  {
   "title": "Connection Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_wan_connection_uptime_seconds{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "uptime" }
     ]
    }
   ]
  },
  {
   "title": "Current Download",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_wan_bytes_receive_rate{instance=~\"$instance\"}*8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "receiverate" }
     ]
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_wan_bytes_send_rate{instance=~\"$instance\"}*8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "sendrate" }
     ]
    }
   ]
  },
  {
   "title": "WAN Connection Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_wan_connection_status{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "constatus" }
     ]
    }
   ]
  },
  {
   "title": "5 GHz Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gateway_wlan2_current_connections{instance=~\"$instance\"}",
     "legendFormat": "5 GHz"
    }
   ]
  },
  {
   "title": "2,4 GHz Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_wlan_current_connections{instance=~\"$instance\"}",
     "legendFormat": "2.4 GHz"
    },
    {
     "expr": "gateway_wlan2_current_connections{instance=~\"$instance\"}",
     "legendFormat": "5 GHz"
    },
    {
     "expr": "gateway_wlan_current_connections{instance=~\"$instance\"}+gateway_wlan2_current_connections{instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DSL Link Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_wan_layer1_link_status{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "fritzbox_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "dslstatus" }
     ]
    }
   ]
  },
  {
   "title": "Total Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "gateway_wan_bytes_received{instance=~\"$instance\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "Total Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "gateway_wan_bytes_sent{instance=~\"$instance\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytessent') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytessent" }
     ]
    }
   ]
  },
  {
   "title": "Network Devices",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gateway_host_active{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Last 24h Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "gateway_wan_bytes_received{instance=~\"$instance\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(max(\"value\")) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytesreceived') AND $timeFilter GROUP BY time($__interval) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "Last 24h Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "gateway_wan_bytes_sent{instance=~\"$instance\"}",
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"value\"))) FROM \"fritzbox_value\" WHERE (\"type_instance\" = 'totalbytessent') AND $timeFilter GROUP BY time($__interval) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytessent" }
     ]
    }
   ]
  },
  {
   "title": "Download Bandwith Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "downstream",
     "expr": "gateway_wan_layer1_downstream_max_bitrate{instance=~\"$instance\"}",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Max. Downstream",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'receiverate' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "receiverate" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-receiverate,'downstream')"
    },
    {
     "alias": "upstream",
     "expr": "gateway_wan_bytes_receive_rate{instance=~\"$instance\"}*8",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Download",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'sendrate' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "sendrate" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-sendrate,'upstream')"
    }
   ]
  },
  {
   "title": "Upload Bandwith Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "downstream max",
     "expr": "gateway_wan_layer1_upstream_max_bitrate{instance=~\"$instance\"}",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Upstream",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'downstreammax' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "downstreammax" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-downstreammax,'downstream max')"
    },
    {
     "alias": "upstream max",
     "expr": "gateway_wan_bytes_send_rate{instance=~\"$instance\"}*8",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Upload",
     "measurement": "fritzbox_value",
     "query": "SELECT mean(value) FROM \"fritzbox_value\" WHERE \"type_instance\" = 'upstreammax' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "upstreammax" }
     ],
     "target": "alias(collectd.squirrel.fritzbox.bitrate-upstreammax,'upstream max')"
    }
   ]
  }
 ]
}