{
 "title": "Mysql - Overview",
 "description": "Basic Mysql dashboard for the prometheus exporter ",
 "tags": [
  "services",
  "mysql",
  "database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "release",
    "label": "Instance",
    "query": "label_values(mysql_up,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Global status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"$release\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{instance=\"$release\"}"
    }
   ]
  },
  {
   "title": "Mysql Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"$release\"}",
     "legendFormat": "current"
    },
    {
     "expr": "mysql_global_variables_max_connections{instance=\"$release\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "mysql  disk reads vs writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_reads{instance=\"$release\"}[10m])",
     "legendFormat": "reads"
    },
    {
     "expr": "irate(mysql_global_status_innodb_data_writes{instance=\"$release\"}[10m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "mysql network received vs sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received{instance=\"$release\"}[5m])",
     "legendFormat": "received"
    },
    {
     "expr": "irate(mysql_global_status_bytes_sent{instance=\"$release\"}[5m])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Query rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_commands_total{instance=\"$release\"}[5m]) > 0",
     "legendFormat": "{{ command }} - {{ release }}"
    }
   ]
  },
  {
   "title": "Running Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_running{instance=\"$release\"} "
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Aborted clients",
   "type": "graph",
   "description": "The number of connections that were aborted because the client died without closing the connection properly. See Section B.5.2.10, “Communication Errors and Aborted Connections”.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_aborted_clients{instance=\"$release\"}"
    }
   ]
  },
  {
   "title": "mysql aborted Connects",
   "type": "graph",
   "description": "The number of failed attempts to connect to the MySQL server. See Section B.5.2.10, “Communication Errors and Aborted Connections”.\n\nFor additional connection-related information, check the Connection_errors_xxx status variables and the host_cache table.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_aborted_connects{instance=\"$release\"}"
    }
   ]
  },
  { "title": "Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Disk usage tables / indexes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_info_schema_table_size{component=\"data_length\",instance=\"$release\"})",
     "legendFormat": "Tables"
    },
    {
     "expr": "sum(mysql_info_schema_table_size{component=\"index_length\",instance=\"$release\"})",
     "legendFormat": "Indexes"
    }
   ]
  },
  {
   "title": "Sum of all rows",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_info_schema_table_rows{instance=\"$release\"})"
    }
   ]
  }
 ]
}