{
 "title": "Nextcloud",
 "description": "Export Nextcloud metrics",
 "tags": [
  "cloud",
  "storage",
  "host"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nextcloud Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nextcloud_system_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Nextcloud Up over time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(nextcloud_up)" }
   ]
  },
  {
   "title": "Free Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nextcloud_free_space_bytes", "legendFormat": "Scrape Errors Total" }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nextcloud_database_size_bytes", "legendFormat": "Scrape Errors Total" }
   ]
  },
  {
   "title": "PHP Memorylimit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nextcloud_php_memory_limit_bytes",
     "legendFormat": "Scrape Errors Total"
    }
   ]
  },
  {
   "title": "PHP Upload Max Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nextcloud_php_upload_max_size_bytes",
     "legendFormat": "Scrape Errors Total"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nextcloud_free_space_bytes" }
   ]
  },
  {
   "title": "PHP Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nextcloud_php_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Auth Errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nextcloud_auth_errors_total", "legendFormat": "Auth Errors Total" },
    {}
   ]
  },
  {
   "title": "Shares",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nextcloud_shares_federated_total)",
     "legendFormat": "Federated Total"
    },
    { "expr": "sum(nextcloud_shares_total)", "legendFormat": "Total Shares" }
   ]
  },
  {
   "title": "Files Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nextcloud_files_total", "legendFormat": "Files Total" }
   ]
  },
  {
   "title": "User Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nextcloud_users_total", "legendFormat": "Users Total" },
    { "expr": "nextcloud_active_users_total", "legendFormat": "Users Active" }
   ]
  },
  {
   "title": "Scrape Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nextcloud_scrape_errors_total", "legendFormat": "Scrape Errors Total" }
   ]
  }
 ]
}