{
 "title": "Nginx",
 "description": "Dashboard for nginx-prometheus-exporter https://github.com/nginxinc/nginx-prometheus-exporter",
 "tags": [
  "nginx",
  "services",
  "web"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up over Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(nginx_up)" }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Reading connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_reading{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Waiting connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 2, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Writing connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_writing{instance=~\"$instance.*\"}"
    }
   ]
  }
 ]
}