{
 "title": "Backup Rsnapshot",
 "tags": [
  "backup",
  "host"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Rsync Status",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rsync_success", "legendFormat": "{{ dst_path }} | Success" }
   ]
  },
  {
   "title": "Backup Start/End",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rsnapshot_start_time * 1000", "legendFormat": "Backup starttime" },
    { "expr": "rsnapshot_end_time * 1000", "legendFormat": "Backup endtime" }
   ]
  },
  {
   "title": "Backup duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "rsnapshot_duration_seconds", "legendFormat": "Backup duration" },
    {
     "expr": "rsync_duration_seconds",
     "legendFormat": "Rsync duration | {{ dst_path }}"
    }
   ]
  },
  {
   "title": "Filelist Generation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "rsync_file_list_gen_seconds", "legendFormat": "Time | {{ dst_path }}" }
   ]
  },
  {
   "title": "Transfered Data",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rsync_total_file_bytes",
     "legendFormat": "Size of all Files  | {{ dst_path }}"
    },
    {
     "expr": "rsync_total_xferred_file_bytes",
     "legendFormat": "Size of transferred Files  | {{ dst_path }}"
    },
    {
     "expr": "rsync_total_sent_bytes",
     "legendFormat": "Size of all Transferred Data  | {{ dst_path }}"
    }
   ]
  },
  {
   "title": "Filecount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rsync_num_files",
     "legendFormat": "Total Number of Files | {{ dst_path }}"
    },
    {
     "expr": "rsync_num_xferred_files",
     "legendFormat": "Files Transferred | {{ dst_path }}"
    }
   ]
  }
 ]
}