{
 "title": "SMART disk data",
 "description": "Extended smartmon Dashboard for disk SMART data",
 "tags": [
  "disk",
  "host"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(smartmon_smartctl_version, instance)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(smartmon_device_smart_available, disk)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(smartmon_device_smart_available, type)"
    }
   },
   {
    "name": "device_model",
    "query": {
     "query": "label_values(smartmon_device_smart_available, device_model)"
    }
   },
   {
    "name": "serial_number",
    "query": {
     "query": "label_values(smartmon_device_smart_available, serial_number)"
    }
   },
   {
    "name": "model_family",
    "query": {
     "query": "label_values(smartmon_device_smart_available, model_family)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SMART DIsk Health",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "smartmon_device_smart_healthy{instance=~\"$instance\"}",
     "legendFormat": "{{ disk }}"
    }
   ]
  },
  {
   "title": "Power on Hours",
   "type": "bargauge",
   "description": "Show Age of Disks, Warning if 5 Years Critical after 7 Years",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nvme_power_on_hours_total) by (device)",
     "legendFormat": "{{ device }}"
    },
    {
     "expr": "max(smartmon_power_on_hours_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\"}) by (disk)",
     "legendFormat": "{{ disk }}"
    }
   ]
  },
  {
   "title": "Pending and Reallocated Sectors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_reallocated_sector_ct_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\"} > 0",
     "legendFormat": "Reallocated {{disk}}"
    },
    {
     "expr": "smartmon_current_pending_sector_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\"} > 0",
     "legendFormat": "Pending {{disk}}"
    }
   ]
  },
  {
   "title": "Total Bytes written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(smartmon_total_lbas_written_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\"} * 4096)",
     "legendFormat": "{{ disk }}"
    },
    {
     "expr": "nvme_data_units_written_total * 4096",
     "legendFormat": "/dev/{{ device }}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_temperature_celsius_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\"}) by (disk)",
     "legendFormat": "{{disk}}"
    },
    {
     "expr": "avg(nvme_temperature_celsius) by (device)",
     "legendFormat": "/dev/{{device}}"
    }
   ]
  },
  {
   "title": "Magnetic Disk Load Cycles",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Cycles" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(smartmon_load_cycle_count_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\"}) by (disk)",
     "legendFormat": "{{ disk }}"
    }
   ]
  },
  {
   "title": "Raw Error Read Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_raw_read_error_rate_raw_value{instance=~\"$instance\",disk=~\"$disk\",type=~\"$type\"}) by (disk) > 0",
     "legendFormat": "{{disk}}"
    },
    {
     "expr": "avg(nvme_media_errors_total) by (device)",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}