{
 "title": "DSL Speedtest",
 "description": "Dashboard for https://github.com/nlamirault/speedtest_exporter",
 "tags": [
  "speedtest",
  "network",
  "external"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second*10^-6",
     "legendFormat": "{{ instance }} | Download Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second*10^-6",
     "legendFormat": "{{ instance }} | Upload Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "{{ instance }} | Ping (ms)"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds",
     "legendFormat": "{{ instance }} | Jitter (ms)"
    }
   ]
  },
  {
   "title": "Server ID tested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ID" } },
   "yaxes": [
    { "format": "ID" }
   ],
   "targets": [
    { "expr": "speedtest_server_id", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}