{
 "title": "Training",
 "tags": [ "external" ],
 "time": { "from": "2021-01-05T00:00:00.000Z", "to": "2021-01-30T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "person", "label": "Wer?", "query": "select person from data" }
  ]
 },
 "panels": [
  {
   "title": "Übungen und Wiederholungen Liegestütze",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   date AS \"time\",   person AS metric,   sum(liegestueze) AS Liegestuez FROM data WHERE person in ($person) AND $__timeFilter(date) GROUP BY person,date,2 ORDER BY date;"
    }
   ]
  },
  {
   "title": "Rangliste Anwesenheit",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select person AS Name,count(person)/3 AS 'mitgemachte Trainings' from data group by person;"
    }
   ]
  },
  {
   "title": "Übungen und Wiederholungen Situps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   date AS \"time\",   person AS metric,   sum(situps) AS Situps FROM data WHERE person in ($person) AND $__timeFilter(date) GROUP BY person,date,2 ORDER BY date;"
    }
   ]
  },
  {
   "title": "Übungen und Wiederholungen Gesamt",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   date AS \"time\",   person AS metric, (sum(liegestueze)+sum(situps)+sum(schwimm)+sum(grizzli)+sum(ccl)+sum(ccr)+sum(ff)+sum(ouino)+sum(kabr)+sum(kniebeuge)) FROM data WHERE person in ($person) AND $__timeFilter(date) GROUP BY person,date,2 ORDER BY date;"
    }
   ]
  },
  {
   "title": "Übungen und Wiederholungen Schwimmer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   date AS \"time\",   person AS metric,   sum(schwimm) FROM data WHERE person in ($person) AND $__timeFilter(date) GROUP BY person,date,2 ORDER BY date;"
    }
   ]
  },
  {
   "title": "Übungen und Wiederholungen Grizzli",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   date AS \"time\",   person AS metric,   sum(grizzli) FROM data WHERE person in ($person) AND $__timeFilter(date) GROUP BY person,date,2 ORDER BY date;"
    }
   ]
  },
  {
   "title": "Übungen und Wiederholungen Cindy Crawford L",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   date AS \"time\",   person AS metric,   sum(ccl) FROM data WHERE person in ($person) AND $__timeFilter(date) GROUP BY person,date,2 ORDER BY date;"
    }
   ]
  },
  {
   "title": "Übungen und Wiederholungen Cindy Crawford R",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   date AS \"time\",   person AS metric,   sum(ccr) FROM data WHERE person in ($person) AND $__timeFilter(date) GROUP BY person,date,2 ORDER BY date;"
    }
   ]
  },
  {
   "title": "Übungen und Wiederholungen F*F*",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   date AS \"time\",   person AS metric,   sum(ff) FROM data WHERE person in ($person) AND $__timeFilter(date) GROUP BY person,date,2 ORDER BY date;"
    }
   ]
  },
  {
   "title": "Übungen und Wiederholungen Oui No",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   date AS \"time\",   person AS metric,   sum(ouino) FROM data WHERE person in ($person) AND $__timeFilter(date) GROUP BY person,date,2 ORDER BY date;"
    }
   ]
  },
  {
   "title": "Übungen und Wiederholungen Karlsbrücke auf/ab",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   date AS \"time\",   person AS metric,   sum(kabr) FROM data WHERE person in ($person) AND $__timeFilter(date) GROUP BY person,date,2 ORDER BY date;"
    }
   ]
  },
  {
   "title": "Übungen und Wiederholungen Kniebeuge",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   date AS \"time\",   person AS metric,   sum(kniebeuge) FROM data WHERE person in ($person) AND $__timeFilter(date) GROUP BY person,date,2 ORDER BY date;"
    }
   ]
  }
 ]
}