{
 "title": "Tasmota Electricity",
 "tags": [
  "external",
  "home",
  "host"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(tasmota_power_watt,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Power Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tasmota_total_power_kwh{instance=\"$instance\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Today Power Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "tasmota_today_power_kwh{instance=\"$instance\"}",
     "legendFormat": "{{ sensor }} - kWh"
    }
   ]
  },
  {
   "title": "Current Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "tasmota_power_watt{instance=\"$instance\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Yesterday Power Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tasmota_yesterday_power_kwh{instance=\"$instance\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Yesterday Power Costs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tasmota_yesterday_power_kwh{instance=\"$instance\"}*0.2867",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Current Volt Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "tasmota_voltage{instance=\"$instance\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Current Ampere Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "tasmota_ampere{instance=\"$instance\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "estimated Power Costs per Year",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time (tasmota_yesterday_power_kwh[1y])*0.2867*365",
     "legendFormat": "{{ sensor }}"
    }
   ]
  }
 ]
}