{
 "title": "Wireguard VPN",
 "tags": [ "services" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(reboot_required, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Handshake",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wireguard_peer_last_handshake_ago_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wireguard_peer_sent_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wireguard_peer_receive_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  }
 ]
}