- name: Check if raid exists
  shell: "mdadm --detail --scan | grep {{ raid_name }}"
  register: "array_check"
  changed_when: false
  failed_when: false
  check_mode: no

- name: creating raid
  shell: |
    yes | mdadm --create {{ raid_name }} --level=1 --raid-devices={{ raid_disks_count }} {{ raid_disks }}
    mdadm --detail --scan {{ raid_name }} >> /etc/mdadm/mdadm.conf
  when: array_check.rc != 0 and raid_disks_count | int > 1